name: Approval Workflow
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  repository_dispatch:
    types: [manual-approval]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Wait for Approval
        id: approval
        uses: bickyshaw98/biceppipline/wait-for-approval@v2
      - name: Deploy if Approved
        if: steps.approval.outputs.approved == 'true'
        run: |
          # Add your deployment steps here
